version: '3.7'
services:
  pipelinedb:
    image: fsonmezay/pipelinedb-postgresql-11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${pg_user}
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: pipeline
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - volume_pg11_pipelinedb:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_pipe
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin_user}
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin_pass}
    volumes:
      - volume_pgadmin_pipelinedb:/var/lib/pgadmin
    links:
      - "pipelinedb:pipelinedba"

volumes:
  volume_pg11_pipelinedb:
  volume_pgadmin_pipelinedb: